[package]
name = "raylib"
version = "0.1.0"
kern = "0.7.5"
description = "Kern bindings for raylib"
readme = "README.md"
license = "MIT"

[lib]
root = "src/lib.rn"

[example]
roots = [
    "examples/basic_window.rn",
]

[test]
roots = [
    "tests/smoke.rn",
    "tests/api_compile.rn",
]

[craft.fmt]
exclude = [
    "src/lib.rn",
    "src/raw.rn",
]

[craft.style]
exclude = [
    "src/lib.rn",
    "src/raw.rn",
]

[resources]
raylib = { git = "https://github.com/raysan5/raylib.git", tag = "6.0" }
